In [3]:
%pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 33.4 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.


In [4]:
%pip install pandas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 27.5 MB/s  0:00:00 eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [5]:
import pandas as pd
import numpy as np

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [6]:
random_list = np.arange(100)

In [7]:
print(random_list[0])

0


In [8]:
print(random_list[5:15])

[ 5  6  7  8  9 10 11 12 13 14]


In [10]:
random_list = random_list * 2

even_list = random_list[random_list % 2 == 0]
print(even_list)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198]


In [11]:
list_2 = np.arange(5)
print(list_2)

[0 1 2 3 4]


In [12]:
print(list_2)

[0 1 2 3 4]


In [13]:
random_array = np.arange(100)

In [14]:
for i in range(51, 101):
    # append 2*1 to every element
    even_list_2 = np.append(arr = random_array, values = 2*i)
    

In [15]:
print(even_list_2)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 200]


In [33]:
#A3 your code here

#1 
test_list = np.array([ -99.52287875, -100.        ,  -99.39794001, -100.        ,
        -99.30103   ,  -99.04575749,  -99.69897   ,  -99.22184875,
        -99.30103   ,  -99.52287875,  -99.30103   ,  -99.09691001,
        -99.04575749,  -99.15490196,  -99.04575749,  -99.52287875,
        -99.69897   ,  -99.52287875,  -99.09691001,  -99.39794001,
        -99.22184875,  -99.69897   ,  -99.22184875,  -99.39794001])

test_list = test_list + 100
test_list

array([0.47712125, 0.        , 0.60205999, 0.        , 0.69897   ,
       0.95424251, 0.30103   , 0.77815125, 0.69897   , 0.47712125,
       0.69897   , 0.90308999, 0.95424251, 0.84509804, 0.95424251,
       0.47712125, 0.30103   , 0.47712125, 0.90308999, 0.60205999,
       0.77815125, 0.30103   , 0.77815125, 0.60205999])

In [34]:
#2

test_list = np.power(10, test_list)
test_list

array([2.99999997, 1.        , 3.99999999, 1.        , 4.99999995,
       9.00000001, 2.00000002, 5.99999999, 4.99999995, 2.99999997,
       4.99999995, 8.00000006, 9.00000001, 7.        , 9.00000001,
       2.99999997, 2.00000002, 2.99999997, 8.00000006, 3.99999999,
       5.99999999, 2.00000002, 5.99999999, 3.99999999])

In [35]:
#3

test_list = np.round(test_list)
test_list

array([3., 1., 4., 1., 5., 9., 2., 6., 5., 3., 5., 8., 9., 7., 9., 3., 2.,
       3., 8., 4., 6., 2., 6., 4.])

In [36]:
#4

test_list[:5]

array([3., 1., 4., 1., 5.])

In [37]:
gapminder = pd.read_csv("gapminder.csv")

In [38]:
print(gapminder)

          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]


In [39]:
#print out the data in the row at idx 1
print(gapminder.iloc[1])

country      Afghanistan
continent           Asia
year                1957
lifeExp           30.332
pop              9240934
gdpPercap      820.85303
Name: 1, dtype: object


In [40]:
print(gapminder.head(5))

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106


In [41]:
print(gapminder.loc[:, "continent"])

0         Asia
1         Asia
2         Asia
3         Asia
4         Asia
         ...  
1699    Africa
1700    Africa
1701    Africa
1702    Africa
1703    Africa
Name: continent, Length: 1704, dtype: str


In [43]:
print(gapminder[["continent", "country", "year"]])

     continent      country  year
0         Asia  Afghanistan  1952
1         Asia  Afghanistan  1957
2         Asia  Afghanistan  1962
3         Asia  Afghanistan  1967
4         Asia  Afghanistan  1972
...        ...          ...   ...
1699    Africa     Zimbabwe  1987
1700    Africa     Zimbabwe  1992
1701    Africa     Zimbabwe  1997
1702    Africa     Zimbabwe  2002
1703    Africa     Zimbabwe  2007

[1704 rows x 3 columns]


In [46]:
#filter a df for specific parts of data
filtered_gapminder = gapminder[(gapminder["year"] > 1980) & gapminder["year"] <= 2000]
filtered_gapminder

country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

In [48]:
great_gapminder = gapminder[(gapminder["country"] == "United States")]
great_gapminder

country continent  year  lifeExp        pop    gdpPercap
1608  United States  Americas  1952   68.440  157553000  13990.48208
1609  United States  Americas  1957   69.490  171984000  14847.12712
1610  United States  Americas  1962   70.210  186538000  16173.14586
1611  United States  Americas  1967   70.760  198712000  19530.36557
1612  United States  Americas  1972   71.340  209896000  21806.03594
1613  United States  Americas  1977   73.380  220239000  24072.63213
1614  United States  Americas  1982   74.650  232187835  25009.55914
1615  United States  Americas  1987   75.020  242803533  29884.35041
1616  United States  Americas  1992   76.090  256894189  32003.93224
1617  United States  Americas  1997   76.810  272911760  35767.43303
1618  United States  Americas  2002   77.310  287675526  39097.09955
1619  United States  Americas  2007   78.242  301139947  42951.65309

In [49]:
great_gapminder = gapminder[(gapminder["year"][3] == 7)]

KeyError: np.False_